// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Mode represents the media authentication mode.
 */
export enum Mode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModeNone = "none",
    ModeBrowser = "browser",
    ModeCookieFile = "cookie_file",
};

/**
 * Settings represents the public media authentication configuration.
 */
export interface Settings {
    "mode": Mode;
    "browser"?: string;
    "profile"?: string;
    "hasCookieFile": boolean;
}
