// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CategoryResponse includes both raw directory and resolved absolute directory for UI consumption.
 */
export interface CategoryResponse {
    "id": string;
    "name": string;
    "directory": string;
    "resolvedDirectory": string;
    "createdAt": string;
    "updatedAt": string;
}
