// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as networkpolicy$0 from "../networkpolicy/models.js";

/**
 * AppError represents an application-level error with a code.
 */
export interface AppError {
    "code": string;
    "message": string;
}

/**
 * BatchItemResult represents the outcome for one item in a batch request.
 */
export interface BatchItemResult {
    "index": number;
    "job"?: Job | null;
    "error"?: AppError | null;
}

/**
 * BulkActionResponse is returned by POST /jobs/bulk.
 */
export interface BulkActionResponse {
    "action": string;
    "succeeded": number;
    "failed": number;
    "results": BulkItemResult[] | null;
}

/**
 * BulkItemResult represents the result for a single job in a bulk operation.
 */
export interface BulkItemResult {
    "jobId": string;
    "success": boolean;
    "job"?: Job | null;
    "error"?: AppError | null;
}

/**
 * CreateBatchResponse is returned by POST /jobs/batch.
 */
export interface CreateBatchResponse {
    "batchId": string;
    "created": number;
    "failed": number;
    "items": BatchItemResult[] | null;
}

/**
 * Event represents an internal event published by the job system.
 */
export interface Event {
    "sequence"?: number;
    "type": string;
    "job": Job;
    "data"?: any;
}

/**
 * FilenameConflictPolicy defines the strategy when a destination file already exists.
 */
export enum FilenameConflictPolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ConflictPolicyRename = "rename",
    ConflictPolicyOverwrite = "overwrite",
    ConflictPolicyFail = "fail",
    ConflictPolicyEngineManaged = "engine_managed",
};

/**
 * Job represents a single download task.
 */
export interface Job {
    "id": string;
    "source": string;
    "name": string;
    "status": JobStatus;
    "type": string;
    "progress": number;
    "totalBytes": number;
    "completedBytes": number;
    "speedBytesPerSecond": number;
    "etaSeconds": number;
    "error"?: string;
    "engine": string;
    "mediaInfo"?: MediaInfo | null;
    "torrentInfo"?: TorrentInfo | null;
    "seedAfterComplete"?: boolean;
    "priority": JobPriority;
    "batchId"?: string;
    "categoryId"?: string;
    "destinationDir": string;
    "workDir"?: string;
    "conflictPolicy": FilenameConflictPolicy;
    "finalPath"?: string;
    "engineCleanupPending"?: boolean;
    "networkPolicy": networkpolicy$0.JobNetworkPolicy;
    "effectiveDownloadLimitBytesPerSecond": number;
    "effectiveUploadLimitBytesPerSecond"?: number;
    "networkReconcilePending"?: boolean;
    "seedingPolicy": networkpolicy$0.SeedingPolicy;
    "seedingStartedAt"?: string | null;
    "seedingStopReason"?: string;
    "customTrackers"?: string[] | null;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * JobPriority represents the queue priority level for a download job.
 */
export enum JobPriority {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    JobPriorityLow = "low",
    JobPriorityNormal = "normal",
    JobPriorityHigh = "high",
};

/**
 * JobStatus represents the state of a download job.
 */
export enum JobStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusQueued = "queued",
    StatusDownloading = "downloading",
    StatusPaused = "paused",
    StatusCompleted = "completed",
    StatusFailed = "failed",
    StatusCancelled = "cancelled",
    StatusAnalyzing = "analyzing",
    StatusProcessing = "processing",
    StatusAwaitingSelection = "awaiting_selection",
    StatusSeeding = "seeding",
};

/**
 * MediaFormat describes a single available format from a media source.
 */
export interface MediaFormat {
    "formatId": string;
    "ext": string;
    "resolution": string;
    "fileSize": number;
    "vcodec": string;
    "acodec": string;
    "fps": number;
    "quality": string;
    "note": string;
    "abr"?: number;
}

/**
 * MediaInfo holds metadata extracted from a media source by yt-dlp.
 */
export interface MediaInfo {
    "title": string;
    "duration": number;
    "thumbnail": string;
    "url": string;
    "formats": MediaFormat[] | null;
    "selectedFormat"?: string;
    "bestAudioFormat"?: MediaFormat | null;
    "subtitles"?: SubtitleCapabilities | null;
    "subtitleOptions"?: SubtitleOptions | null;
}

/**
 * QueueAction defines whether a queued job requires a fresh engine start or a resume operation.
 */
export enum QueueAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    QueueActionStart = "start",
    QueueActionResume = "resume",
};

/**
 * QueueSnapshot represents the response for GET /queue.
 */
export interface QueueSnapshot {
    "maxConcurrentDownloads": number;
    "runningDownloads": number;
    "queuedDownloads": number;
    "pausedDownloads": number;
    "items": QueuedJob[] | null;
}

/**
 * QueuedJob combines a Job with its QueueEntry and derived runtime waiting reason.
 */
export interface QueuedJob {
    "jobId": string;
    "position": number;
    "action": QueueAction;
    "retryCount"?: number;
    "notBefore"?: string | null;
    "enqueuedAt": string;
    "updatedAt": string;
    "waitingReason"?: string;
    "job": Job;
}

/**
 * SubtitleCapabilities represents the subtitle capabilities discovered during analysis.
 */
export interface SubtitleCapabilities {
    "tracks": SubtitleTrack[] | null;
    "englishTranslationAvailable": boolean;
}

/**
 * SubtitleFormat represents the requested subtitle format.
 */
export enum SubtitleFormat {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SubtitleFormatSRT = "srt",
    SubtitleFormatVTT = "vtt",
};

/**
 * SubtitleMode represents the output mode for downloaded subtitles.
 */
export enum SubtitleMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SubtitleModeSeparate = "separate",
    SubtitleModeEmbed = "embed",
    SubtitleModeBoth = "both",
};

/**
 * SubtitleOptions holds the user's requested subtitle configuration for a media download.
 */
export interface SubtitleOptions {
    "languages"?: string[] | null;
    "includeAuto"?: boolean;
    "englishTranslation"?: boolean;
    "mode"?: SubtitleMode;
    "format"?: SubtitleFormat;
}

/**
 * SubtitleTrack represents a normalized subtitle track available for a media source.
 */
export interface SubtitleTrack {
    "language": string;
    "name"?: string;
    "manual": boolean;
    "auto": boolean;
    "formats"?: string[] | null;
}

/**
 * SyncSnapshot provides an authoritative snapshot of server jobs and queue state
 * along with the monotonic cursor watermark.
 */
export interface SyncSnapshot {
    "cursor": number;
    "jobs": Job[] | null;
    "queue": QueueSnapshot | null;
    "timestamp": string;
}

/**
 * TorrentFile represents a single file within a torrent.
 */
export interface TorrentFile {
    "index": number;
    "path": string;
    "size": number;
    "progress": number;
    "priority": TorrentFilePriority;
    "selected": boolean;
}

/**
 * TorrentFilePriority represents the priority level for a torrent file.
 */
export enum TorrentFilePriority {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PrioritySkip = "skip",
    PriorityNormal = "normal",
    PriorityHigh = "high",
    PriorityMaximum = "maximum",
};

/**
 * TorrentInfo holds normalized torrent metadata owned by GoDownloader.
 */
export interface TorrentInfo {
    "name": string;
    "infoHash": string;
    "totalSize": number;
    "seeders": number;
    "leechers": number;
    "uploaded": number;
    "uploadSpeed": number;
    "ratio": number;
    "seedingTimeSeconds": number;
}
