// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopService exposes the unified GoDownloader application runtime
 * to the embedded desktop frontend via Wails v3 in-process IPC.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as job$0 from "../../internal/job/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mediaauth$0 from "../../internal/mediaauth/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as networkpolicy$0 from "../../internal/networkpolicy/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../../internal/settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../../internal/storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddTorrentTrackers(id: string, trackers: string[] | null): $CancellablePromise<$models.TrackersResult | null> {
    return $Call.ByID(2801585035, id, trackers);
}

export function BulkAction(action: string, jobIDs: string[] | null): $CancellablePromise<job$0.BulkActionResponse | null> {
    return $Call.ByID(773919159, action, jobIDs);
}

export function CancelJob(id: string): $CancellablePromise<job$0.Job | null> {
    return $Call.ByID(673696146, id);
}

export function CreateBatchJobs(inputsJSON: string): $CancellablePromise<job$0.CreateBatchResponse | null> {
    return $Call.ByID(374493675, inputsJSON);
}

export function CreateCategory(name: string, directory: string): $CancellablePromise<storage$0.CategoryResponse | null> {
    return $Call.ByID(1406001193, name, directory);
}

export function CreateJob(source: string, priority: string, categoryID: string, destinationDir: string, conflictPolicy: string, networkPolicyJSON: string, seedingPolicyJSON: string, trackers: string[] | null): $CancellablePromise<job$0.Job | null> {
    return $Call.ByID(2010946212, source, priority, categoryID, destinationDir, conflictPolicy, networkPolicyJSON, seedingPolicyJSON, trackers);
}

export function CreateTrackerSource(name: string, url: string, enabled: boolean, refreshIntervalSeconds: number): $CancellablePromise<networkpolicy$0.TrackerSource | null> {
    return $Call.ByID(463320502, name, url, enabled, refreshIntervalSeconds);
}

export function DeleteCategory(id: string): $CancellablePromise<void> {
    return $Call.ByID(3558105058, id);
}

export function DeleteJob(id: string, deleteFiles: boolean): $CancellablePromise<void> {
    return $Call.ByID(3610361997, id, deleteFiles);
}

export function DeleteMediaCookies(): $CancellablePromise<mediaauth$0.Settings | null> {
    return $Call.ByID(1935531969);
}

export function DeleteTrackerSource(id: string): $CancellablePromise<void> {
    return $Call.ByID(2218491311, id);
}

/**
 * EmitDiagnosticEvent publishes a deterministic diagnostic event across the application event bus.
 */
export function EmitDiagnosticEvent(token: string): $CancellablePromise<void> {
    return $Call.ByID(4230022879, token);
}

export function GetBackendInstanceID(): $CancellablePromise<string> {
    return $Call.ByID(80028127);
}

export function GetCapabilities(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1664152477);
}

export function GetCategories(): $CancellablePromise<storage$0.CategoryResponse[] | null> {
    return $Call.ByID(1044235979);
}

export function GetDataRootInfo(): $CancellablePromise<$models.DataRootInfo | null> {
    return $Call.ByID(4187956567);
}

/**
 * GetDiagnosticEventDeliveryCount returns the delivery count for the last emitted diagnostic event.
 */
export function GetDiagnosticEventDeliveryCount(): $CancellablePromise<number> {
    return $Call.ByID(2667844939);
}

export function GetEventsAfter(cursor: number): $CancellablePromise<$models.EventsReplayResult | null> {
    return $Call.ByID(2397380008, cursor);
}

export function GetJob(id: string): $CancellablePromise<job$0.Job | null> {
    return $Call.ByID(2401552206, id);
}

export function GetJobCapabilities(id: string): $CancellablePromise<networkpolicy$0.JobCapabilities> {
    return $Call.ByID(2130254848, id);
}

export function GetJobs(): $CancellablePromise<job$0.Job[] | null> {
    return $Call.ByID(2481300743);
}

export function GetMediaAuthSettings(): $CancellablePromise<mediaauth$0.Settings | null> {
    return $Call.ByID(1992411246);
}

export function GetQueueSnapshot(): $CancellablePromise<job$0.QueueSnapshot | null> {
    return $Call.ByID(3910836674);
}

export function GetSettings(): $CancellablePromise<settings$0.AppSettings | null> {
    return $Call.ByID(682518218);
}

export function GetSingleInstanceStatus(): $CancellablePromise<$models.SingleInstanceStatus | null> {
    return $Call.ByID(2874737574);
}

export function GetSyncSnapshot(): $CancellablePromise<job$0.SyncSnapshot | null> {
    return $Call.ByID(1420917508);
}

export function GetTorrentFiles(id: string): $CancellablePromise<job$0.TorrentFile[] | null> {
    return $Call.ByID(2855949114, id);
}

export function GetTrackerSources(): $CancellablePromise<networkpolicy$0.TrackerSource[] | null> {
    return $Call.ByID(753764301);
}

export function ImportMediaCookies(content: string): $CancellablePromise<mediaauth$0.Settings | null> {
    return $Call.ByID(3671726167, content);
}

export function OpenFolder(): $CancellablePromise<void> {
    return $Call.ByID(4251953865);
}

export function PauseJob(id: string): $CancellablePromise<job$0.Job | null> {
    return $Call.ByID(2560643508, id);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(1821349302);
}

/**
 * RecordDiagnosticDelivery records an event delivery acknowledged by the frontend.
 */
export function RecordDiagnosticDelivery(token: string): $CancellablePromise<void> {
    return $Call.ByID(1556007099, token);
}

/**
 * RecordStateSyncCompleted records completion of frontend StateSync initialization or catch-up.
 */
export function RecordStateSyncCompleted(cursor: number): $CancellablePromise<void> {
    return $Call.ByID(1972263043, cursor);
}

export function RefreshAllTrackerSources(): $CancellablePromise<$models.TrackerRefreshSummary | null> {
    return $Call.ByID(3975827205);
}

export function RefreshTrackerSource(id: string): $CancellablePromise<networkpolicy$0.TrackerSource | null> {
    return $Call.ByID(3126597693, id);
}

/**
 * ReloadMainWindow forces a reload of the main webview window.
 */
export function ReloadMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(3005123689);
}

export function ReorderQueue(priority: string, jobIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1536549095, priority, jobIDs);
}

export function ResolveCapabilities(sourceJSON: string): $CancellablePromise<networkpolicy$0.JobCapabilities> {
    return $Call.ByID(3255059649, sourceJSON);
}

export function ResumeJob(id: string): $CancellablePromise<job$0.Job | null> {
    return $Call.ByID(2744292589, id);
}

export function RetryJob(id: string): $CancellablePromise<job$0.Job | null> {
    return $Call.ByID(2692776144, id);
}

export function SelectFormat(id: string, formatID: string, subtitleOptionsJSON: string): $CancellablePromise<job$0.Job | null> {
    return $Call.ByID(3691919834, id, formatID, subtitleOptionsJSON);
}

export function SetJobPriority(id: string, priority: string): $CancellablePromise<job$0.Job | null> {
    return $Call.ByID(492972990, id, priority);
}

export function ShowNativeDialog(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3514873491, title, message);
}

export function StartTorrent(id: string, filesJSON: string, seedingPolicyJSON: string): $CancellablePromise<job$0.Job | null> {
    return $Call.ByID(2758672875, id, filesJSON, seedingPolicyJSON);
}

export function StopSeeding(id: string): $CancellablePromise<job$0.Job | null> {
    return $Call.ByID(2549687116, id);
}

export function UpdateCategory(id: string, name: string, directory: string): $CancellablePromise<storage$0.CategoryResponse | null> {
    return $Call.ByID(2318623788, id, name, directory);
}

export function UpdateJobNetwork(id: string, limitsJSON: string): $CancellablePromise<job$0.Job | null> {
    return $Call.ByID(2892368911, id, limitsJSON);
}

export function UpdateMediaAuthSettings(reqJSON: string): $CancellablePromise<mediaauth$0.Settings | null> {
    return $Call.ByID(2728391971, reqJSON);
}

export function UpdateSeedingPolicy(id: string, policyJSON: string): $CancellablePromise<job$0.Job | null> {
    return $Call.ByID(2604069489, id, policyJSON);
}

export function UpdateSettings(settingsJSON: string): $CancellablePromise<settings$0.AppSettings | null> {
    return $Call.ByID(1174076825, settingsJSON);
}

export function UpdateTrackerSource(id: string, name: string, url: string, enabled: boolean, refreshIntervalSeconds: number): $CancellablePromise<networkpolicy$0.TrackerSource | null> {
    return $Call.ByID(1828869501, id, name, url, enabled, refreshIntervalSeconds);
}

export function UploadTorrent(filename: string, base64Data: string, priority: string, categoryID: string, destinationDir: string, networkPolicyJSON: string, seedingPolicyJSON: string, trackers: string[] | null): $CancellablePromise<job$0.Job | null> {
    return $Call.ByID(1595690570, filename, base64Data, priority, categoryID, destinationDir, networkPolicyJSON, seedingPolicyJSON, trackers);
}
