// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as job$0 from "../../internal/job/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as networkpolicy$0 from "../../internal/networkpolicy/models.js";

/**
 * DataRootInfo holds metadata about resolved desktop data directories.
 */
export interface DataRootInfo {
    "executablePath": string;
    "workingDir": string;
    "resolvedDataRoot": string;
    "isDeterministic": boolean;
}

/**
 * EventsReplayResult contains events replayed since a requested cursor.
 */
export interface EventsReplayResult {
    "events": job$0.Event[] | null;
    "currentCursor": number;
    "gapDetected": boolean;
}

/**
 * SingleInstanceStatus holds status information about the primary instance and secondary launches.
 */
export interface SingleInstanceStatus {
    "primaryPid": number;
    "coreInitCount": number;
    "secondLaunchCount": number;
    "lastForwardedArgs": string[] | null;
    "lastForwardedCwd": string;
}

/**
 * TrackerRefreshSummary carries summary info for tracker refresh operations.
 */
export interface TrackerRefreshSummary {
    "failureCount": number;
}

/**
 * TrackersResult carries tracker results for addTorrentTrackers.
 */
export interface TrackersResult {
    "trackers": networkpolicy$0.Tracker[] | null;
}
