// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CapabilityState {
    "supported": boolean;
    "mutableNow": boolean;
    "startupOnly"?: boolean;
    "reason"?: string;
    "supportedProtocols"?: string[] | null;
    "supportedFields"?: string[] | null;
}

export interface DirectConnectionPolicy {
    "split": number;
    "maxConnectionsPerServer": number;
    "minSplitSizeBytes": number;
}

export interface HTTPHeader {
    "name": string;
    "value"?: string;
    "hasValue"?: boolean;
    "sensitive"?: boolean;
    "clearValue"?: boolean;
}

export interface JobCapabilities {
    "pause": CapabilityState;
    "resume": CapabilityState;
    "cancel": CapabilityState;
    "retry": CapabilityState;
    "downloadLimit": CapabilityState;
    "uploadLimit": CapabilityState;
    "proxy": CapabilityState;
    "userAgent": CapabilityState;
    "customHeaders": CapabilityState;
    "retryPolicy": CapabilityState;
    "timeoutPolicy": CapabilityState;
    "connections": CapabilityState;
    "fileSelection": CapabilityState;
    "trackers": CapabilityState;
    "seedingPolicy": CapabilityState;
}

export interface JobNetworkPolicy {
    "downloadLimitBytesPerSecond": number;
    "uploadLimitBytesPerSecond"?: number;
    "proxy": ProxyPolicy;
    "userAgent"?: string;
    "httpHeaders"?: HTTPHeader[] | null;
    "retryPolicy": RetryPolicy;
    "timeoutPolicy": TimeoutPolicy;
    "directConnections"?: DirectConnectionPolicy | null;
}

export interface NetworkSettings {
    "globalDownloadLimitBytesPerSecond": number;
    "proxy": ProxyPolicy;
    "userAgent": string;
    "httpHeaders": HTTPHeader[] | null;
    "retryPolicy": RetryPolicy;
    "timeoutPolicy": TimeoutPolicy;
    "directConnections": DirectConnectionPolicy;
}

export enum ProxyMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProxyModeDisabled = "disabled",
    ProxyModeSystem = "system",
    ProxyModeCustom = "custom",
};

export interface ProxyPolicy {
    "mode": ProxyMode;
    "protocol"?: ProxyProtocol;
    "host"?: string;
    "port"?: number;
    "username"?: string;
    "hasPassword"?: boolean;
    "secretSource"?: string;
    "noProxy"?: string[] | null;
}

export enum ProxyProtocol {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProxyProtocolHTTP = "http",
    ProxyProtocolHTTPS = "https",
    ProxyProtocolSOCKS5 = "socks5",
};

export interface RetryPolicy {
    "maxAttempts": number;
    "retryWaitSeconds": number;
}

export enum SeedingMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SeedingModeNone = "none",
    SeedingModeUnlimited = "unlimited",
    SeedingModeRatio = "ratio",
    SeedingModeDuration = "duration",
    SeedingModeRatioOrDuration = "ratio_or_duration",
};

export interface SeedingPolicy {
    "mode": SeedingMode;
    "ratioLimit"?: number | null;
    "timeLimitSeconds"?: number | null;
}

export interface TimeoutPolicy {
    "connectTimeoutSeconds": number;
    "requestTimeoutSeconds": number;
}

export interface TorrentSettings {
    "downloadLimitBytesPerSecond": number;
    "uploadLimitBytesPerSecond": number;
    "seedingPolicy": SeedingPolicy;
    "applyTrackerSubscriptionsToNewTorrents": boolean;
    "manageQBitGlobalNetworkSettings": boolean;
}

export interface Tracker {
    "url": string;
    "status"?: number;
    "msg"?: string;
}

export interface TrackerSource {
    "id": string;
    "name": string;
    "url": string;
    "enabled": boolean;
    "refreshIntervalSeconds": number;
    "lastCheckedAt"?: string | null;
    "lastSuccessAt"?: string | null;
    "lastError"?: string;
    "trackerCount": number;
    "createdAt": string;
    "updatedAt": string;
}
