// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as networkpolicy$0 from "../networkpolicy/models.js";

/**
 * AppSettings represents user-configurable application settings.
 */
export interface AppSettings {
    "queue": QueueSettings;
    "storage": StorageSettings;
    "network": networkpolicy$0.NetworkSettings;
    "torrent": networkpolicy$0.TorrentSettings;
    "overrides"?: { [_ in string]?: boolean } | null;
    "applicationResults"?: ApplicationResult[] | null;
}

export interface ApplicationResult {
    "target": string;
    "status": string;
    "code"?: string;
    "message"?: string;
}

/**
 * QueueSettings represents the queue configuration settings.
 */
export interface QueueSettings {
    "maxConcurrentDownloads": number;
    "effectiveMaxConcurrentDownloads": number;
    "environmentOverride": boolean;
}

/**
 * StorageOverrides indicates which storage settings have active environment overrides.
 */
export interface StorageOverrides {
    "defaultDownloadDirectory": boolean;
    "temporaryDirectory": boolean;
    "minimumFreeSpaceBytes": boolean;
    "defaultConflictPolicy": boolean;
}

/**
 * StorageSettings represents storage lifecycle configuration settings.
 */
export interface StorageSettings {
    "defaultDownloadDirectory": string;
    "effectiveDefaultDownloadDirectory": string;
    "temporaryDirectory": string;
    "effectiveTemporaryDirectory": string;
    "minimumFreeSpaceBytes": number;
    "effectiveMinimumFreeSpaceBytes": number;
    "defaultConflictPolicy": string;
    "effectiveDefaultConflictPolicy": string;
    "overrides": StorageOverrides;
}
